# Generated by Django 3.2.23 on 2024-01-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_modify_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='modify_date',
            new_name='modified_date',
        ),
    ]
