# Generated by Django 4.2.7 on 2025-03-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_ip_address_alter_account_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
