# Generated by Django 4.2.7 on 2025-03-10 14:36

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_is_superuser_account_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='58.91599192355906,25.400390625', max_length=63),
        ),
    ]
