# Generated by Django 4.2.7 on 2025-03-23 08:35

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='58.91599192355906,25.400390625', max_length=63),
        ),
    ]
