# Generated by Django 4.2.7 on 2024-11-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='modified_date',
        ),
    ]
