# Generated by Django 3.2.23 on 2024-01-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_logo',
            field=models.ImageField(default=1, upload_to='client_pictures'),
            preserve_default=False,
        ),
    ]
